/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-16-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

public class address {
    public void homeaddress(){

        String yourName = 'Adem Adem';
        system.debug('My name is '+ yourName);

        Integer numberOfMembers = 5;
        system.debug('my family is consist ' + numberOfMembers +'person' );

        string houseName = 'Adems House';
        system.debug('We live on '+ houseName);

        String houseNumber = ''



    }
}
