/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-27-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class TurkishLesson5 {
    public static void listMethod(){
        List<String> dersList = new List<String>();
    dersList.add('Math');
    dersList.add('Art');
    system.debug(dersList.size());
    system.debug(dersList.get(1));
    }
    
}
